# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# disable JSON schema validation for VSCode
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

# Site
title: 果果闪光堆放处
subtitle: 赛博痒痒挠 专治不舒服
description: "@enihsyou 编写中>>>"
author: 九条涼果
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.kokomi.me
root: /
permalink: posts/:id/
permalink_defaults:
pretty_urls:
  trailing_index: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
include:
  - _redirects
exclude:
  # 作为源代码使用
  - images/travel-moe-logo.png

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

syntax_highlighter: highlight.js
highlight:
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: false
  hljs: true
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

#Feed
## hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

#Search
search:
  path: search.xml
  field: post
  format: html
  limit: 50

#Sitemap
#sitemap:
#  path: sitemap.xml
#  template: ./sitemap_template.xml

#hexo-generator-category
category_generator:
  per_page: 10

#hexo-generator-archive
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

#hexo-generator-index
index_generator:
  path: ""
  per_page: 5
  order_by: -date

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: "v"
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

## Hexo-minify Default Config Options
minify:
  preview: false ## 本地预览时是否压缩
  exclude: ['*.min.*']
  js:
    enable: true
    sourceMap:
      enable: false ## 生成 sourceMap
      ## 将 sourceMappingURL 插入压缩后的 js 文件，如果为 false 则需要在浏览器开发者工具中手动添加 sourceMap
      sourceMappingURL: false ## //# sourceMappingURL=xxx.js.map
    ## 详细配置: https://github.com/terser/terser#minify-options
    options: {}
  css:
    enable: true
    ## 详细配置: https://github.com/clean-css/clean-css#compatibility-modes
    options: {}
  html:
    enable: true
    ## 详细配置: https://github.com/kangax/html-minifier#options-quick-reference
    options:
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  image:
    enable: false
  font:
    # 即便如此也需要强制设置版本 "fonteditor-core": "2.1.11"
    enable: false